//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarNombreUsuario {
            get {
                return ((string)(this["GuardarNombreUsuario"]));
            }
            set {
                this["GuardarNombreUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCodigoUsuario {
            get {
                return ((string)(this["GuardarCodigoUsuario"]));
            }
            set {
                this["GuardarCodigoUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCodigoPerfil {
            get {
                return ((string)(this["GuardarCodigoPerfil"]));
            }
            set {
                this["GuardarCodigoPerfil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarNombrePerfil {
            get {
                return ((string)(this["GuardarNombrePerfil"]));
            }
            set {
                this["GuardarNombrePerfil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarClaveUsuario {
            get {
                return ((string)(this["GuardarClaveUsuario"]));
            }
            set {
                this["GuardarClaveUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCodigoEmpresa {
            get {
                return ((string)(this["GuardarCodigoEmpresa"]));
            }
            set {
                this["GuardarCodigoEmpresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarNombreEmpresa {
            get {
                return ((string)(this["GuardarNombreEmpresa"]));
            }
            set {
                this["GuardarNombreEmpresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCheckUsuario {
            get {
                return ((string)(this["GuardarCheckUsuario"]));
            }
            set {
                this["GuardarCheckUsuario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCheckClave {
            get {
                return ((string)(this["GuardarCheckClave"]));
            }
            set {
                this["GuardarCheckClave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarCheckEmpresa {
            get {
                return ((string)(this["GuardarCheckEmpresa"]));
            }
            set {
                this["GuardarCheckEmpresa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoIngresos {
            get {
                return ((string)(this["GuardarPeriodoIngresos"]));
            }
            set {
                this["GuardarPeriodoIngresos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoSalidas {
            get {
                return ((string)(this["GuardarPeriodoSalidas"]));
            }
            set {
                this["GuardarPeriodoSalidas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoTransferencias {
            get {
                return ((string)(this["GuardarPeriodoTransferencias"]));
            }
            set {
                this["GuardarPeriodoTransferencias"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GuardarPeriodoMovimientos {
            get {
                return ((string)(this["GuardarPeriodoMovimientos"]));
            }
            set {
                this["GuardarPeriodoMovimientos"] = value;
            }
        }
    }
}
